apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-10-11 - 02:27:05 +0000
  labels:
    app.kubernetes.io/name: smart-iot
    app.kubernetes.io/version: "1.0"
  name: smart-iot
  namespace: iot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: smart-iot
      app.kubernetes.io/version: "1.0"
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2022-10-11 - 02:27:05 +0000
      labels:
        app.kubernetes.io/name: smart-iot
        app.kubernetes.io/version: "1.0"
      namespace: iot-dev
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quarkus/smart-iot:1.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: smart-iot
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 45
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 64Mi